Если в try..catch будет return, всё, что ниже, не будет выполнено. А при использовании finally - блок совершенно точно будет вызван и пройден.